In [1]:
import pandas as pd
import numpy as np

In [3]:
data ={
    "name": ["max","snappy","slappy","aki","abhi"],
    "age": [25,30,np.nan,49,70,],
    "city": ["pune","pune","pune","tamilnadu","karnataka"]

}
print(data)
df = pd.DataFrame(data)
df
df.info()
df.head()

{'name': ['max', 'snappy', 'slappy', 'aki', 'abhi'], 'age': [25, 30, nan, 49, 70], 'city': ['pune', 'pune', 'pune', 'tamilnadu', 'karnataka']}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     4 non-null      float64
 2   city    5 non-null      object
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes

     name   age       city
0     max  25.0       pune
1  snappy  30.0       pune
2  slappy   NaN       pune
3     aki  49.0  tamilnadu
4    abhi  70.0  karnataka

In [4]:
print("mean of the age:")
print(df["age"].mean())
print("median of the age:")
print(df["age"].median())
print("mode of the age:")
print(df["age"].mode)

mean of the age:
43.5
median of the age:
39.5
mode of the age:
<bound method Series.mode of 0    25.0
1    30.0
2     NaN
3    49.0
4    70.0
Name: age, dtype: float64>

In [13]:
new_data ={
    "name": ["max","snappy","slappy","aki","abhi"],
    "age": [25,30,np.nan,49,70,],
    "salary": [1,2,3,4,5]

}
print(new_data)
df = pd.DataFrame(new_data)
df
df.info()
df.head()

{'name': ['max', 'snappy', 'slappy', 'aki', 'abhi'], 'age': [25, 30, nan, 49, 70], 'salary': [1, 2, 3, 4, 5]}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     4 non-null      float64
 2   salary  5 non-null      int64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes

     name   age  salary
0     max  25.0       1
1  snappy  30.0       2
2  slappy   NaN       3
3     aki  49.0       4
4    abhi  70.0       5

In [14]:
df[["age","salary"]]= df[["age","salary"]].fillna(df[["age","salary"]]).mean()
df

/tmp/ipykernel_3117/3573338178.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df[["age","salary"]]= df[["age","salary"]].fillna(df[["age","salary"]]).mean()

     name   age  salary
0     max  43.5     3.0
1  snappy  43.5     3.0
2  slappy  43.5     3.0
3     aki  43.5     3.0
4    abhi  43.5     3.0